[package]
authors = [
    "Clark Kampfe"
]
edition = "2018"
name = "pm"
readme = "README.md"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4"
wasm-bindgen = "^0.2"
wee_alloc = "0.4.5"
yew = { git = "https://github.com/yewstack/yew" }
